### ISSUE TITLE
Documentation Request: There is a "dotnet tool" and this is how to use it!

### ISSUE THREAD

**Issue by PureKrome** [codecov/codecov-exe#88]
Hi 👋 

I just stumbled on the fact that Codecov has a `dotnet tool` ! this is _awesome_ because we should be able to use Codecov on linux CI images! Even if someone is using a windows image this would be awesome, still.

So could the README.md please get an update so we don't need to use Chocolatey now? 

![](https://media.giphy.com/media/fmkp70c7IIb9C/giphy.gif)

**Comment by AdmiringWorm** [comment]
@PureKrome I have made some small changes to the Readme documentation here: https://github.com/codecov/codecov-exe/blob/better-tool-docs/README.md (Won't be available by default until the next version of codecov-exe is released).

I am terrible when it comes to documentation, so if you would be willing to have a look I would appreciate it.

**Comment by PureKrome** [comment]
Woot - had a full read and that helps.

As a side note: I would promote the `dotnet tool` solution as the proper way because then it's a _consistent_ experience across platforms (x-plat) and offer the `choco` way as an option "obsolete" way for existing window OS's users.

**Comment by AdmiringWorm** [comment]
The `choco` way is still the recommended way to install `codecov-exe`, especially if doing only windows builds.

For cross-platform builds it is actually recommended to use the [`Codecov` nuget package](https://www.nuget.org/packages/Codecov), the .net core tool is added more for convenience than anything else and for those not able to use any of the other packages.

All of the available packages (or downloading directly from github releases) provides the exact experience no matter what platform it is running on (with the exception of the installation of course).

The reason why either the chocolatey package, or the normal nuget package is recommended is because these two have undergone the most of testing in quite a few projects compared to the .NET Core tool, as well as those are completely standalone executables. The recommendation may change in the future, but not yet.
